# Generated by Django 5.0.14 on 2026-01-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0002_load_sourceswitchevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorreading",
            name="sensor_type",
            field=models.CharField(
                choices=[
                    ("ldr", "Light Dependent Resistor"),
                    ("current", "Current Sensor"),
                    ("temperature", "Temperature Sensor"),
                    ("humidity", "Humidity Sensor"),
                    ("voltage", "Voltage Sensor"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
